### ISSUE TITLE
Short circuiting not implemented in requires-expression

### ISSUE THREAD

**Issue by saarraz** [saarraz/clang-concepts-old#24]
Substitution into requires expression requirements does not terminate when satisfaction is determined: https://godbolt.org/z/tpU4_Z

**Comment by marehr** [comment]
I think we hit the same issue:

```c++
#include <tuple>

#if __cpp_concepts == 201507 // GCC and Concepts TS
#define concept concept bool
#endif

template <typename tuple_t>
concept tuple_size_concept = requires (tuple_t v)
{
    { std::tuple_size<tuple_t>::value } -> std::size_t;
};

template <typename tuple_t>
concept tuple_get_concept = requires (tuple_t & v, tuple_t const & v_c)
{
    requires std::tuple_size_v<tuple_t> > 0;

    typename std::tuple_element<0, tuple_t>::type;
    { std::get<0>(v)              } -> typename std::tuple_element<0, tuple_t>::type &;
    { std::get<0>(v_c)            } -> typename std::tuple_element<0, tuple_t>::type const &;
    { std::get<0>(std::move(v))   } -> typename std::tuple_element<0, tuple_t>::type &&;
    { std::get<0>(std::move(v_c)) };
};

template <typename tuple_t>
concept tuple_like_concept = tuple_size_concept<tuple_t> && requires(tuple_t tuple)
{
    requires (std::tuple_size<tuple_t>::value == 0) || tuple_get_concept<tuple_t>;
};

static_assert(tuple_like_concept<std::tuple<int>>);
static_assert(tuple_like_concept<std::tuple<>>); // fails

```

https://godbolt.org/z/ZnnW5k

**Comment by saarraz** [comment]
Fixed in latest commit.

**Comment by marehr** [comment]
My example is still not working with your most recent compiler version

But, changing

```c++
template <typename tuple_t>
concept tuple_like_concept = tuple_size_concept<tuple_t> && requires(tuple_t tuple)
{
    requires (std::tuple_size<tuple_t>::value == 0) || tuple_get_concept<tuple_t>;
};
```
to
```c++
template <typename tuple_t>
concept tuple_like_concept = tuple_size_concept<tuple_t> && (std::tuple_size<tuple_t>::value == 0 || requires(tuple_t tuple)
{
    requires  tuple_get_concept<tuple_t>;
});
```

works now.

I would expect that you have short circuits in the requires clause.

**Comment by saarraz** [comment]
Compiler Explorer did not update yet, the first version should work as well with the fix.

**Comment by marehr** [comment]
Ah I'm sorry, I forgot to install the fresh compiled version; I'll try again!

**Comment by marehr** [comment]
Okay; Confirmed this works now; Thank you!
